"""initial schema

Revision ID: a9b0f154a532
Revises: 
Create Date: 2026-09-04 15:07:08.572626
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import app.db_types


revision: str = 'a9b0f154a532'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gym_capacity', sa.Integer(), nullable=False),
    sa.Column('default_booking_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('booking_step_minutes', sa.Integer(), nullable=False),
    sa.Column('cancel_before_minutes', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('updated_at', app.db_types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_blocks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('start_at', app.db_types.UTCDateTime(), nullable=False),
    sa.Column('end_at', app.db_types.UTCDateTime(), nullable=False),
    sa.Column('type', sa.Enum('maintenance', 'private_event', 'closed', 'other', name='bookingblocktype', native_enum=False), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', app.db_types.UTCDateTime(), nullable=False),
    sa.CheckConstraint('end_at > start_at', name='ck_booking_block_valid_interval'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_booking_blocks_interval', 'booking_blocks', ['start_at', 'end_at'], unique=False)
    op.create_table('membership_types',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('visits_package', 'unlimited', name='membershipkind', native_enum=False), nullable=False),
    sa.Column('visits_count', sa.Integer(), nullable=True),
    sa.Column('validity_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_slots',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('start_at', app.db_types.UTCDateTime(), nullable=False),
    sa.Column('end_at', app.db_types.UTCDateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db_types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db_types.UTCDateTime(), nullable=False),
    sa.CheckConstraint('end_at > start_at', name='ck_schedule_slot_valid_interval'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_schedule_slots_interval', 'schedule_slots', ['start_at', 'end_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('client', 'trainer', 'admin', name='userrole', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db_types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db_types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('measurements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('measured_at', app.db_types.UTCDateTime(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('body_fat', sa.Float(), nullable=True),
    sa.Column('muscle_mass', sa.Float(), nullable=True),
    sa.Column('created_at', app.db_types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_measurements_user_measured', 'measurements', ['user_id', 'measured_at'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('membership_type_id', sa.String(length=36), nullable=False),
    sa.Column('starts_at', app.db_types.UTCDateTime(), nullable=False),
    sa.Column('expires_at', app.db_types.UTCDateTime(), nullable=True),
    sa.Column('visits_total', sa.Integer(), nullable=True),
    sa.Column('visits_remaining', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'expired', 'cancelled', name='membershipstatus', native_enum=False), nullable=False),
    sa.Column('created_at', app.db_types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db_types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['membership_type_id'], ['membership_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memberships_user_status', 'memberships', ['user_id', 'status'], unique=False)
    op.create_table('trainer_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('trainer_id', sa.String(length=36), nullable=True),
    sa.Column('schedule_slot_id', sa.String(length=80), nullable=True),
    sa.Column('start_at', app.db_types.UTCDateTime(), nullable=False),
    sa.Column('end_at', app.db_types.UTCDateTime(), nullable=False),
    sa.Column('status', sa.Enum('confirmed', 'cancelled', 'completed', 'no_show', name='bookingstatus', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancelled_at', app.db_types.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.db_types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db_types.UTCDateTime(), nullable=False),
    sa.CheckConstraint('end_at > start_at', name='ck_booking_valid_interval'),
    sa.ForeignKeyConstraint(['schedule_slot_id'], ['schedule_slots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainer_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bookings_interval_status', 'bookings', ['start_at', 'end_at', 'status'], unique=False)
    op.create_index('ix_bookings_trainer_interval', 'bookings', ['trainer_id', 'start_at', 'end_at'], unique=False)
    op.create_table('trainer_specialties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trainer_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trainer_id', 'name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainer_specialties')
    op.drop_index('ix_bookings_trainer_interval', table_name='bookings')
    op.drop_index('ix_bookings_interval_status', table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('trainer_profiles')
    op.drop_index('ix_memberships_user_status', table_name='memberships')
    op.drop_table('memberships')
    op.drop_index('ix_measurements_user_measured', table_name='measurements')
    op.drop_table('measurements')
    op.drop_table('users')
    op.drop_index('ix_schedule_slots_interval', table_name='schedule_slots')
    op.drop_table('schedule_slots')
    op.drop_table('membership_types')
    op.drop_index('ix_booking_blocks_interval', table_name='booking_blocks')
    op.drop_table('booking_blocks')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
